### ISSUE TITLE
ThumbParamsOSC.exe crashes at startup

### ISSUE THREAD

**Issue by BitiTiger** [I5UCC/VRCThumbParamsOSC#18] opened 2024-09-16 22:04 UTC
If you need more information than I provided, please let me know.

# Setup
- Windows 11 23H2
- Valve Index
- SteamVR 2.7.4

# Steps to reproduce
- Download latest release
- Extract zip file
- Run `Configurator.exe`
- Click `Reset OSC Config`
- Click `Save`
- Close `Configurator.exe`
- Run `ThumbParamsOSC.exe`
- *program crashes*

# Output log
```txt
16-Sep-24 17:44:36 - INFO - OpenVR Initialized.
16-Sep-24 17:44:36 - INFO - Application Manifest Added.
16-Sep-24 17:44:36 - INFO - ThumbParamsOSC v2.3.1 running...
16-Sep-24 17:44:36 - INFO - IP: 127.0.0.1
16-Sep-24 17:44:36 - INFO - Port: 9000
16-Sep-24 17:44:36 - INFO - Server Port: 0
16-Sep-24 17:44:36 - INFO - HTTP Port: 0
16-Sep-24 17:44:36 - INFO - PollingRate: 0.04s (25 Hz)
16-Sep-24 17:44:36 - INFO - StickMoveTolerance: 0.05 (5%)
16-Sep-24 17:44:36 - INFO - Open Configurator.exe to change sent Parameters and other Settings.
16-Sep-24 17:44:36 - ERROR - UNEXPECTED ERROR

16-Sep-24 17:44:36 - ERROR - Please Create an Issue on GitHub with the following information:

16-Sep-24 17:44:36 - ERROR - Traceback (most recent call last):
  File "main.py", line 311, in <module>
  File "main.py", line 304, in main_loop
  File "main.py", line 141, in handle_input
  File "D:\GitRepos\VRCThumbParamsOSC\src\ovr.py", line 90, in poll_next_events
  File "D:\GitRepos\VRCThumbParamsOSC\.venv\Lib\site-packages\openvr\__init__.py", line 6711, in updateActionState
  File "D:\GitRepos\VRCThumbParamsOSC\.venv\Lib\site-packages\openvr\error_code\__init__.py", line 23, in check_error_value
openvr.error_code.InputError_NoData
```

**Comment by I5UCC** [comment] 2024-09-17 17:08
@BitiTiger Currently a common issue. Using [v2.2.1](https://github.com/I5UCC/VRCThumbParamsOSC/releases/tag/v2.2.1) seems to be working fine until i figure out the issue!

**Comment by I5UCC** [comment] 2024-09-17 17:23
@BitiTiger Actually, your steps to reproduce really helped figuring out what the issue was. The configurator ended up saving a config file with some missing entries, it should be fixed in [the newest version](https://github.com/I5UCC/VRCThumbParamsOSC/releases/tag/v2.3.2)! Thanks for the input ❤️

**Closed as completed by I5UCC** 2024-09-17 17:23 UTC
